import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { SiteShell } from "@/components/SiteShell";
import { siteConfig } from "@/config/site";

const title = "Pharmacy Reconciliation & Prescription Renewal ML Platform";
const description = "An end-to-end Applied ML system for leakage-safe prescription-renewal prediction, operational follow-up workflows, and containerized deployment using entirely synthetic pharmacy data.";
const repository = "https://github.com/suuuhailllkhann/pharmacy-reconciliation-ml";

export const metadata: Metadata = {
  title: `${title} | Suhail`, description, alternates: { canonical: "/projects/pharmacy-reconciliation-ml" },
  openGraph: { title, description, url: `${siteConfig.url}/projects/pharmacy-reconciliation-ml`, siteName: "Suhail — Portfolio", type: "article", images: [] },
  twitter: { card: "summary", title, description, images: [] },
};

const nav = [["overview", "Overview"], ["problem", "Problem"], ["methodology", "Methodology"], ["evaluation", "Evaluation"], ["engineering", "ML engineering"], ["architecture", "Architecture"], ["decisions", "Decisions"], ["limitations", "Limitations"]] as const;
const methods = ["Deterministic longitudinal synthetic data", "Point-in-time prediction design", "Leakage prevention", "Chronological Train / Validation / Test split", "16-feature final model input", "Train-only preprocessing", "Time-series cross-validation", "Logistic Regression / Random Forest / XGBoost / LightGBM comparison", "Locked final Logistic Regression before Test", "Threshold = 0.50", "Test consumed once"];
const metrics = [["63.83%", "Accuracy"], ["63.06%", "Precision"], ["90.83%", "Recall"], ["74.44%", "F1"], ["73.52%", "PR-AUC"], ["67.10%", "ROC-AUC"]];
const engineering = ["MLflow experiment tracking and locked model artifact", "FastAPI single and batch inference", "PostgreSQL prediction history", "Follow-up case workflow", "Activities and explicit case resolution", "Alembic migrations", "Docker and Docker Compose", "Persistent PostgreSQL volume", "Health and readiness endpoints", "Request IDs and privacy-safe logs", "139 automated tests", "GitHub Actions CI"];
const decisions = [["Chronology first", "Used chronological splitting instead of a random split to preserve the temporal prediction setting."], ["Locked before Test", "Selected the model and 0.50 threshold before consuming Test, with no Test-based retuning."], ["Synthetic by design", "All longitudinal pharmacy records and reported model results are deterministic and synthetic."], ["Prefer interpretable", "Selected simpler Logistic Regression after comparison with more complex tree-based models."], ["Human resolution", "Cases require explicit operational resolution rather than automatic closure from model output."]];
const limitations = [["Synthetic data only", "The system has not been evaluated on real pharmacy data."], ["Not a clinical model", "Predictions support a simulated operational review workflow, not clinical decisions."], ["Not production deployed", "The validated system runs locally with Docker Compose."], ["AWS is planning only", "The AWS path is future architecture and has not been deployed."], ["No real-world claim", "The reported metrics do not represent real pharmacy performance."]];
const architectureStages = [["Synthetic data", "Fixed-seed longitudinal histories"], ["Feature engineering", "Point-in-time features"], ["Leakage-safe temporal ML", "Chronological validation"], ["Locked Logistic Regression", "Threshold 0.50"], ["MLflow", "Locked model artifact"], ["FastAPI", "Single and batch inference"], ["PostgreSQL", "Predictions and follow-up cases"], ["Docker Compose", "Validated local system"]];

function SectionTitle({ label, children }: { label: string; children: React.ReactNode }) { return <><span className="mono-label">{label}</span><h2>{children}</h2></>; }

export default function PharmacyReconciliationProjectPage() {
  return <SiteShell><main id="main-content">
    <section className="case-hero pharmacy-case-hero"><div className="container">
      <Link className="back-link" href="/#projects">← Selected work</Link><div className="status"><i /> Applied ML platform · synthetic data only</div>
      <h1>{title}</h1><p>{description}</p>
      <ul className="tag-list case-tags">{["Python", "scikit-learn", "MLflow", "FastAPI", "PostgreSQL", "Docker"].map((tag) => <li key={tag}>{tag}</li>)}</ul>
      <div className="case-actions"><Link className="button button-light" href="#overview">Explore project ↓</Link><a className="text-link case-repo-link" href={repository} target="_blank" rel="noreferrer">View GitHub ↗</a></div>
      <div className="case-meta"><div><span>Data</span><strong>100% synthetic</strong></div><div><span>Final model</span><strong>Logistic Regression</strong></div><div><span>Delivery</span><strong>Validated locally · not deployed</strong></div></div>
    </div></section>
    <div className="case-layout container"><aside><span className="mono-label">On this page</span><nav aria-label="Case study sections">{nav.map(([id, label], index) => <Link href={`#${id}`} key={id}>{String(index + 1).padStart(2, "0")} {label}</Link>)}</nav></aside>
      <div className="case-content">
        <section id="overview" className="case-section"><SectionTitle label="01 / Overview">From reconciliation workflow to an operational ML platform.</SectionTitle><p>The project began as a pharmacy billing-vs-ordering reconciliation workflow and evolved into an end-to-end Applied ML system for prescription-renewal prediction and operational follow-up.</p><div className="synthetic-banner"><strong>Synthetic evidence boundary</strong><span>Every record, prediction, and reported model result in this project is synthetic.</span></div></section>
        <section id="problem" className="case-section"><SectionTitle label="02 / Problem">Two connected operational questions.</SectionTitle><div className="scope-grid"><article><span className="mono-label">Reconciliation</span><h3>Billed vs ordered quantities</h3><p>Compare medication quantities to surface shortages, overages, and records that need operational review.</p></article><article><span className="mono-label">Renewal review</span><h3>Zero-refill prescriptions</h3><p>Identify prescriptions that may need renewal review as expected medication supply approaches exhaustion.</p></article></div><div className="callout"><strong>System role:</strong> prioritize operational follow-up for human review—not provide clinical guidance or automatically close cases.</div></section>
        <section id="methodology" className="case-section"><SectionTitle label="03 / Applied ML methodology">Designed around time, leakage prevention, and a locked Test.</SectionTitle><ol className="method-grid">{methods.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></li>)}</ol></section>
        <section id="evaluation" className="case-section"><SectionTitle label="04 / Final synthetic evaluation">Recall-first results, without real-world claims.</SectionTitle><div className="metric-grid pharmacy-metrics">{metrics.map(([value, label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><figure className="case-figure"><Image src="/pharmacy-synthetic-evaluation.svg" alt="Bar chart of final model metrics on the locked synthetic Test set" width={1000} height={560} /><figcaption>Locked Logistic Regression evaluation on synthetic Test observations.</figcaption></figure><p className="case-note"><strong>Interpretation:</strong> high recall means the model caught most synthetic renewal cases, with the trade-off of additional false-positive review workload. This is not clinical or real-world performance.</p></section>
        <section id="engineering" className="case-section"><SectionTitle label="05 / ML engineering">Built beyond the model artifact.</SectionTitle><div className="engineering-grid">{engineering.map((item, index) => <article key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></article>)}</div></section>
        <section id="architecture" className="case-section"><SectionTitle label="06 / Architecture">Validated locally, with the future path kept separate.</SectionTitle><figure className="case-figure architecture-figure"><Image src="/pharmacy-system-architecture.svg" alt="Local platform architecture with a separately labeled future AWS path" width={1400} height={510} /><figcaption>Current local architecture and future infrastructure are intentionally separated.</figcaption></figure><div className="mobile-architecture" aria-label="Validated local system architecture"><span className="mono-label">Validated local system</span><ol>{architectureStages.map(([name, detail], index) => <li key={name}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{name}</strong><small>{detail}</small></div></li>)}</ol></div><div className="future-callout"><span>Future architecture — not deployed</span><p>AWS components shown in the diagram are planning only and are not represented as deployed technology.</p></div></section>
        <section id="decisions" className="case-section"><SectionTitle label="07 / Key engineering decisions">Constraints made explicit.</SectionTitle><div className="decision-list">{decisions.map(([heading, copy], index) => <article key={heading}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{heading}</h3><p>{copy}</p></div></article>)}</div></section>
        <section id="limitations" className="case-section"><SectionTitle label="08 / Limitations">What this work does not claim.</SectionTitle><div className="limitation-grid pharmacy-limitations">{limitations.map(([heading, copy]) => <article key={heading}><h3>{heading}</h3><p>{copy}</p></article>)}</div></section>
      </div>
    </div>
    <section className="case-cta"><div className="container"><span className="eyebrow">Technical implementation</span><h2>Explore the complete system.</h2><p>The repository contains the synthetic-data pipeline, trained model workflow, API, migrations, tests, operational case handling, and Docker Compose setup.</p><a className="button button-light" href={repository} target="_blank" rel="noreferrer">View repository ↗</a></div></section>
  </main></SiteShell>;
}
